### consulta de todos los usuarios 
GET http://localhost:4500/users
Content-Type: application/json

### usuarios un suario en particular    
POST http://localhost:4500/login
Content-Type: application/json

{
    "email": "usuario2@correo.com",
    "password": "pas"
}

### usuarios un suario en particular no existente
GET http://localhost:4500/users/"usuario3@correo.com"&"password1"
Content-Type: application/json

### usuarios
POST http://localhost:4500/create
Content-Type: application/json

    {
        "email": "hoy@correo.com",
        "password": "hoy"
    }

### usuarios
POST http://localhost:4500/login
Content-Type: application/json

    {
        "email": "billy@example.com",
        "password": "passaword1"
    }

### recibos
POST http://localhost:4500/api/v1/recibos/
Content-Type: application/json

    {
        "user_id": 1,
        "email": "billy@example.com",
        "password": "passaword1"
    }

### cobros
POST http://localhost:4500/api/v1/recibos/stripe/
Content-Type: application/json

    {
        "user_id": 1,
        "email": "billy@example.com",
        "password": "passaword1"
    }
